// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnwgpIhk59IRPiJij6yoFwK34UbP-LgVY',
    appId: '1:40200608427:web:d7040a9c9f26b4fad935ee',
    messagingSenderId: '40200608427',
    projectId: 'k-o-solar-erp',
    authDomain: 'k-o-solar-erp.firebaseapp.com',
    storageBucket: 'k-o-solar-erp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFlPpOzi-q9L94H4iGXmTY7333NxUN5gI',
    appId: '1:40200608427:android:860885ea20793aa4d935ee',
    messagingSenderId: '40200608427',
    projectId: 'k-o-solar-erp',
    storageBucket: 'k-o-solar-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsriUiWQdaMTm0ufXldeVoHOgB-uMl2gk',
    appId: '1:40200608427:ios:0d0442eb5fedc81ed935ee',
    messagingSenderId: '40200608427',
    projectId: 'k-o-solar-erp',
    storageBucket: 'k-o-solar-erp.firebasestorage.app',
    iosBundleId: 'com.kosolar.koSolarErp',
  );

}